//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int Status_id { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public int PickupPoint_id { get; set; }
        public int GetCode { get; set; }
        public Nullable<int> Client_id { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual PickupPoint PickupPoint { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
    }
}
